from env.sawyer.sawyer_reach import SawyerReachEnv
from env.sawyer.sawyer_reach_obstacle import SawyerReachObstacleEnv
from env.sawyer.sawyer_reach_float_obstacle import SawyerReachFloatObstacleEnv
from env.sawyer.sawyer_assembly_easy import SawyerAssemblyEasyEnv
from env.sawyer.sawyer_push import SawyerPushEnv
from env.sawyer.sawyer_push_obstacle import SawyerPushObstacleEnv
from env.sawyer.sawyer_push_obstacle_easy import SawyerPushObstacleEasyEnv
from env.sawyer.sawyer_peg_insertion import SawyerPegInsertionEnv


